version: "3.7"
services:
  app:
    build:
      args:
        user: www
        uid: 1000
      context: ./
      dockerfile: docker-compose/php/Dockerfile
    image: app-php
    # 複数プロジェクトの場合、container_name重複しないように
    container_name: app-appname
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker-compose/php/php.ini:/usr/local/etc/php/php.ini

  db:
    # image: mysql:5.7
    image: mysql:8
    container_name: db-appname
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports: 
      - "3307:3306"
    volumes:
      # - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: nginx-appname
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d

volumes:
  mysql-data:
